credentials:
  users:
    - name: "John Doe"
      username: "johndoe"
      password: "password"
    - name: "Jane Smith"
      username: "janesmith"
      password: "password"

cookie:
  name: "my_cookie"
  key: "my_cookie_key"
  expiry_days: 30

preauthorized:
  emails: []
